name: Merge Master

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: bumpTag
      uses: anothrNick/github-tag-action@1.18.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
    - name: printTag
      env:
        GIT_TAG: ${{ steps.bumpTag.outputs.tag }}
      run: echo "$GIT_TAG"
